apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50

